name: github pages

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 20 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn
      - run: yarn build
      - run: yarn rss --token=${{ secrets.GH_TOKEN }} --site-title=浮之静 --site-link=https://z.nofwl.com --site-desc="浮之静 技术社区"
      - run: yarn woap

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./dist
